/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminOrgSlugRouteImport } from './routes/admin.$orgSlug'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as OrgSlugCCompetitionIdRouteImport } from './routes/$orgSlug.c.$competitionId'
import { Route as AdminOrgSlugIndexRouteImport } from './routes/admin.$orgSlug.index'
import { Route as AdminOrgSlugDivisionsRouteImport } from './routes/admin.$orgSlug.divisions'
import { Route as AdminOrgSlugPeopleRouteImport } from './routes/admin.$orgSlug.people'
import { Route as AdminOrgSlugSeasonsRouteImport } from './routes/admin.$orgSlug.seasons'
import { Route as AdminOrgSlugVenuesRouteImport } from './routes/admin.$orgSlug.venues'
import { Route as AdminOrgSlugCompetitionsIndexRouteImport } from './routes/admin.$orgSlug.competitions.index'
import { Route as AdminOrgSlugCompetitionsCompetitionIdRouteImport } from './routes/admin.$orgSlug.competitions.$competitionId'
import { Route as AdminOrgSlugTeamsIndexRouteImport } from './routes/admin.$orgSlug.teams.index'
import { Route as AdminOrgSlugTeamsTeamIdRouteImport } from './routes/admin.$orgSlug.teams.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/$orgSlug/',
  path: '/$orgSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgSlugRoute = AdminOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugCCompetitionIdRoute = OrgSlugCCompetitionIdRouteImport.update({
  id: '/$orgSlug/c/$competitionId',
  path: '/$orgSlug/c/$competitionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrgSlugIndexRoute = AdminOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrgSlugRoute,
} as any)
const AdminOrgSlugDivisionsRoute = AdminOrgSlugDivisionsRouteImport.update({
  id: '/divisions',
  path: '/divisions',
  getParentRoute: () => AdminOrgSlugRoute,
} as any)
const AdminOrgSlugPeopleRoute = AdminOrgSlugPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminOrgSlugRoute,
} as any)
const AdminOrgSlugSeasonsRoute = AdminOrgSlugSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => AdminOrgSlugRoute,
} as any)
const AdminOrgSlugVenuesRoute = AdminOrgSlugVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AdminOrgSlugRoute,
} as any)
const AdminOrgSlugCompetitionsIndexRoute =
  AdminOrgSlugCompetitionsIndexRouteImport.update({
    id: '/competitions/',
    path: '/competitions/',
    getParentRoute: () => AdminOrgSlugRoute,
  } as any)
const AdminOrgSlugCompetitionsCompetitionIdRoute =
  AdminOrgSlugCompetitionsCompetitionIdRouteImport.update({
    id: '/competitions/$competitionId',
    path: '/competitions/$competitionId',
    getParentRoute: () => AdminOrgSlugRoute,
  } as any)
const AdminOrgSlugTeamsIndexRoute = AdminOrgSlugTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AdminOrgSlugRoute,
} as any)
const AdminOrgSlugTeamsTeamIdRoute = AdminOrgSlugTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AdminOrgSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/admin/$orgSlug': typeof AdminOrgSlugRouteWithChildren
  '/admin/new': typeof AdminNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$orgSlug/c/$competitionId': typeof OrgSlugCCompetitionIdRoute
  '/admin/$orgSlug/divisions': typeof AdminOrgSlugDivisionsRoute
  '/admin/$orgSlug/people': typeof AdminOrgSlugPeopleRoute
  '/admin/$orgSlug/seasons': typeof AdminOrgSlugSeasonsRoute
  '/admin/$orgSlug/venues': typeof AdminOrgSlugVenuesRoute
  '/admin/$orgSlug/': typeof AdminOrgSlugIndexRoute
  '/admin/$orgSlug/competitions/$competitionId': typeof AdminOrgSlugCompetitionsCompetitionIdRoute
  '/admin/$orgSlug/teams/$teamId': typeof AdminOrgSlugTeamsTeamIdRoute
  '/admin/$orgSlug/competitions/': typeof AdminOrgSlugCompetitionsIndexRoute
  '/admin/$orgSlug/teams/': typeof AdminOrgSlugTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/admin/new': typeof AdminNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$orgSlug/c/$competitionId': typeof OrgSlugCCompetitionIdRoute
  '/admin/$orgSlug/divisions': typeof AdminOrgSlugDivisionsRoute
  '/admin/$orgSlug/people': typeof AdminOrgSlugPeopleRoute
  '/admin/$orgSlug/seasons': typeof AdminOrgSlugSeasonsRoute
  '/admin/$orgSlug/venues': typeof AdminOrgSlugVenuesRoute
  '/admin/$orgSlug': typeof AdminOrgSlugIndexRoute
  '/admin/$orgSlug/competitions/$competitionId': typeof AdminOrgSlugCompetitionsCompetitionIdRoute
  '/admin/$orgSlug/teams/$teamId': typeof AdminOrgSlugTeamsTeamIdRoute
  '/admin/$orgSlug/competitions': typeof AdminOrgSlugCompetitionsIndexRoute
  '/admin/$orgSlug/teams': typeof AdminOrgSlugTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/admin/$orgSlug': typeof AdminOrgSlugRouteWithChildren
  '/admin/new': typeof AdminNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$orgSlug/c/$competitionId': typeof OrgSlugCCompetitionIdRoute
  '/admin/$orgSlug/divisions': typeof AdminOrgSlugDivisionsRoute
  '/admin/$orgSlug/people': typeof AdminOrgSlugPeopleRoute
  '/admin/$orgSlug/seasons': typeof AdminOrgSlugSeasonsRoute
  '/admin/$orgSlug/venues': typeof AdminOrgSlugVenuesRoute
  '/admin/$orgSlug/': typeof AdminOrgSlugIndexRoute
  '/admin/$orgSlug/competitions/$competitionId': typeof AdminOrgSlugCompetitionsCompetitionIdRoute
  '/admin/$orgSlug/teams/$teamId': typeof AdminOrgSlugTeamsTeamIdRoute
  '/admin/$orgSlug/competitions/': typeof AdminOrgSlugCompetitionsIndexRoute
  '/admin/$orgSlug/teams/': typeof AdminOrgSlugTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/me'
    | '/admin/$orgSlug'
    | '/admin/new'
    | '/auth/callback'
    | '/$orgSlug/'
    | '/admin/'
    | '/$orgSlug/c/$competitionId'
    | '/admin/$orgSlug/divisions'
    | '/admin/$orgSlug/people'
    | '/admin/$orgSlug/seasons'
    | '/admin/$orgSlug/venues'
    | '/admin/$orgSlug/'
    | '/admin/$orgSlug/competitions/$competitionId'
    | '/admin/$orgSlug/teams/$teamId'
    | '/admin/$orgSlug/competitions/'
    | '/admin/$orgSlug/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/me'
    | '/admin/new'
    | '/auth/callback'
    | '/$orgSlug'
    | '/admin'
    | '/$orgSlug/c/$competitionId'
    | '/admin/$orgSlug/divisions'
    | '/admin/$orgSlug/people'
    | '/admin/$orgSlug/seasons'
    | '/admin/$orgSlug/venues'
    | '/admin/$orgSlug'
    | '/admin/$orgSlug/competitions/$competitionId'
    | '/admin/$orgSlug/teams/$teamId'
    | '/admin/$orgSlug/competitions'
    | '/admin/$orgSlug/teams'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/me'
    | '/admin/$orgSlug'
    | '/admin/new'
    | '/auth/callback'
    | '/$orgSlug/'
    | '/admin/'
    | '/$orgSlug/c/$competitionId'
    | '/admin/$orgSlug/divisions'
    | '/admin/$orgSlug/people'
    | '/admin/$orgSlug/seasons'
    | '/admin/$orgSlug/venues'
    | '/admin/$orgSlug/'
    | '/admin/$orgSlug/competitions/$competitionId'
    | '/admin/$orgSlug/teams/$teamId'
    | '/admin/$orgSlug/competitions/'
    | '/admin/$orgSlug/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugCCompetitionIdRoute: typeof OrgSlugCCompetitionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/$orgSlug'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$orgSlug': {
      id: '/admin/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/admin/$orgSlug'
      preLoaderRoute: typeof AdminOrgSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/c/$competitionId': {
      id: '/$orgSlug/c/$competitionId'
      path: '/$orgSlug/c/$competitionId'
      fullPath: '/$orgSlug/c/$competitionId'
      preLoaderRoute: typeof OrgSlugCCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$orgSlug/': {
      id: '/admin/$orgSlug/'
      path: '/'
      fullPath: '/admin/$orgSlug/'
      preLoaderRoute: typeof AdminOrgSlugIndexRouteImport
      parentRoute: typeof AdminOrgSlugRoute
    }
    '/admin/$orgSlug/divisions': {
      id: '/admin/$orgSlug/divisions'
      path: '/divisions'
      fullPath: '/admin/$orgSlug/divisions'
      preLoaderRoute: typeof AdminOrgSlugDivisionsRouteImport
      parentRoute: typeof AdminOrgSlugRoute
    }
    '/admin/$orgSlug/people': {
      id: '/admin/$orgSlug/people'
      path: '/people'
      fullPath: '/admin/$orgSlug/people'
      preLoaderRoute: typeof AdminOrgSlugPeopleRouteImport
      parentRoute: typeof AdminOrgSlugRoute
    }
    '/admin/$orgSlug/seasons': {
      id: '/admin/$orgSlug/seasons'
      path: '/seasons'
      fullPath: '/admin/$orgSlug/seasons'
      preLoaderRoute: typeof AdminOrgSlugSeasonsRouteImport
      parentRoute: typeof AdminOrgSlugRoute
    }
    '/admin/$orgSlug/venues': {
      id: '/admin/$orgSlug/venues'
      path: '/venues'
      fullPath: '/admin/$orgSlug/venues'
      preLoaderRoute: typeof AdminOrgSlugVenuesRouteImport
      parentRoute: typeof AdminOrgSlugRoute
    }
    '/admin/$orgSlug/competitions/': {
      id: '/admin/$orgSlug/competitions/'
      path: '/competitions'
      fullPath: '/admin/$orgSlug/competitions/'
      preLoaderRoute: typeof AdminOrgSlugCompetitionsIndexRouteImport
      parentRoute: typeof AdminOrgSlugRoute
    }
    '/admin/$orgSlug/competitions/$competitionId': {
      id: '/admin/$orgSlug/competitions/$competitionId'
      path: '/competitions/$competitionId'
      fullPath: '/admin/$orgSlug/competitions/$competitionId'
      preLoaderRoute: typeof AdminOrgSlugCompetitionsCompetitionIdRouteImport
      parentRoute: typeof AdminOrgSlugRoute
    }
    '/admin/$orgSlug/teams/': {
      id: '/admin/$orgSlug/teams/'
      path: '/teams'
      fullPath: '/admin/$orgSlug/teams/'
      preLoaderRoute: typeof AdminOrgSlugTeamsIndexRouteImport
      parentRoute: typeof AdminOrgSlugRoute
    }
    '/admin/$orgSlug/teams/$teamId': {
      id: '/admin/$orgSlug/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/admin/$orgSlug/teams/$teamId'
      preLoaderRoute: typeof AdminOrgSlugTeamsTeamIdRouteImport
      parentRoute: typeof AdminOrgSlugRoute
    }
  }
}

interface AdminOrgSlugRouteChildren {
  AdminOrgSlugDivisionsRoute: typeof AdminOrgSlugDivisionsRoute
  AdminOrgSlugPeopleRoute: typeof AdminOrgSlugPeopleRoute
  AdminOrgSlugSeasonsRoute: typeof AdminOrgSlugSeasonsRoute
  AdminOrgSlugVenuesRoute: typeof AdminOrgSlugVenuesRoute
  AdminOrgSlugIndexRoute: typeof AdminOrgSlugIndexRoute
  AdminOrgSlugCompetitionsCompetitionIdRoute: typeof AdminOrgSlugCompetitionsCompetitionIdRoute
  AdminOrgSlugTeamsTeamIdRoute: typeof AdminOrgSlugTeamsTeamIdRoute
  AdminOrgSlugCompetitionsIndexRoute: typeof AdminOrgSlugCompetitionsIndexRoute
  AdminOrgSlugTeamsIndexRoute: typeof AdminOrgSlugTeamsIndexRoute
}

const AdminOrgSlugRouteChildren: AdminOrgSlugRouteChildren = {
  AdminOrgSlugDivisionsRoute: AdminOrgSlugDivisionsRoute,
  AdminOrgSlugPeopleRoute: AdminOrgSlugPeopleRoute,
  AdminOrgSlugSeasonsRoute: AdminOrgSlugSeasonsRoute,
  AdminOrgSlugVenuesRoute: AdminOrgSlugVenuesRoute,
  AdminOrgSlugIndexRoute: AdminOrgSlugIndexRoute,
  AdminOrgSlugCompetitionsCompetitionIdRoute:
    AdminOrgSlugCompetitionsCompetitionIdRoute,
  AdminOrgSlugTeamsTeamIdRoute: AdminOrgSlugTeamsTeamIdRoute,
  AdminOrgSlugCompetitionsIndexRoute: AdminOrgSlugCompetitionsIndexRoute,
  AdminOrgSlugTeamsIndexRoute: AdminOrgSlugTeamsIndexRoute,
}

const AdminOrgSlugRouteWithChildren = AdminOrgSlugRoute._addFileChildren(
  AdminOrgSlugRouteChildren,
)

interface AdminRouteChildren {
  AdminOrgSlugRoute: typeof AdminOrgSlugRouteWithChildren
  AdminNewRoute: typeof AdminNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrgSlugRoute: AdminOrgSlugRouteWithChildren,
  AdminNewRoute: AdminNewRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugCCompetitionIdRoute: OrgSlugCCompetitionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
