/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminOrgSlugRouteImport } from './routes/admin.$orgSlug'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminOrgSlugIndexRouteImport } from './routes/admin.$orgSlug.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgSlugRoute = AdminOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrgSlugIndexRoute = AdminOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrgSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/$orgSlug': typeof AdminOrgSlugRouteWithChildren
  '/admin/new': typeof AdminNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$orgSlug/': typeof AdminOrgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/new': typeof AdminNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/admin/$orgSlug': typeof AdminOrgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/$orgSlug': typeof AdminOrgSlugRouteWithChildren
  '/admin/new': typeof AdminNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$orgSlug/': typeof AdminOrgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/$orgSlug'
    | '/admin/new'
    | '/auth/callback'
    | '/admin/'
    | '/admin/$orgSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/new'
    | '/auth/callback'
    | '/admin'
    | '/admin/$orgSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/$orgSlug'
    | '/admin/new'
    | '/auth/callback'
    | '/admin/'
    | '/admin/$orgSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$orgSlug': {
      id: '/admin/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/admin/$orgSlug'
      preLoaderRoute: typeof AdminOrgSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$orgSlug/': {
      id: '/admin/$orgSlug/'
      path: '/'
      fullPath: '/admin/$orgSlug/'
      preLoaderRoute: typeof AdminOrgSlugIndexRouteImport
      parentRoute: typeof AdminOrgSlugRoute
    }
  }
}

interface AdminOrgSlugRouteChildren {
  AdminOrgSlugIndexRoute: typeof AdminOrgSlugIndexRoute
}

const AdminOrgSlugRouteChildren: AdminOrgSlugRouteChildren = {
  AdminOrgSlugIndexRoute: AdminOrgSlugIndexRoute,
}

const AdminOrgSlugRouteWithChildren = AdminOrgSlugRoute._addFileChildren(
  AdminOrgSlugRouteChildren,
)

interface AdminRouteChildren {
  AdminOrgSlugRoute: typeof AdminOrgSlugRouteWithChildren
  AdminNewRoute: typeof AdminNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrgSlugRoute: AdminOrgSlugRouteWithChildren,
  AdminNewRoute: AdminNewRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
